version: '3.4'
services:   
  database:
    image: postgres:14.8-alpine
    container_name: eni_database
    restart: on-failure
    env_file: .env
    ports:
      - 54321:5432
    volumes:
      - eni_data:/var/lib/postgresql/data
  cache:
    image: "redis:7-alpine3.18"
    container_name: eni_cache
    restart: on-failure
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes: 
      - eni_data:/data
  server:
      container_name: eni_server
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - 8080:8080
      restart: on-failure
      depends_on:
        - database
        - cache
        - besu_node
        - teku_node      
      links:
        - database
      networks:
        - eniapp
  besu_node:
    image: hyperledger/besu:latest
    command:
      [
        "--network=sepolia",
        "--data-path=/var/lib/besu/data",
        "--host-allowlist=*",
        "--sync-mode=FAST",
        "--rpc-http-enabled",
        "--rpc-http-cors-origins=*",
        "--rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3",
        "--engine-jwt-secret=/var/lib/besu/data/token.txt",
        "--engine-host-allowlist=*",
        "--engine-rpc-enabled=true",
      ]
    volumes:
      - ./besu:/var/lib/besu/data
    ports:
      # Map the p2p port(30303), RPC HTTP port(8545), and engine port (8551)
      - "8545:8545"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
  teku_node:
    environment:
      - "JAVA_OPTS=-Xmx4g"
    image: consensys/teku:latest
    command:
      [
        "--network=sepolia",
        "--data-base-path=/var/lib/teku/data",
        "--validators-proposer-default-fee-recipient=0xEe23212c0aE64a719EaD573D64831873A1f8a012",
        "--ee-endpoint=http://besu_node:8551",
        "--ee-jwt-secret-file=/var/lib/teku/data/token.txt",
        "--validator-keys=/var/lib/teku/data/validator/keys:/var/lib/teku/data/validator/passwords",
        "--p2p-port=9000",
        "--rest-api-enabled=true",
        "--rest-api-docs-enabled=true",
        "--rest-api-cors-origins=*"
      ]
    depends_on:
      - besu_node
    volumes:
      - ./teku:/var/lib/teku/data
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5051:5051"

volumes:
  eni_data:
  
# Networks to be created to facilitate communication between containers
networks:
  eniapp:
    driver: bridge