package consts

type EnvE string

const (
	API_HOST EnvE ="API_HOST"
	API_PORT EnvE ="API_PORT")
const (
	POSTGRES_USER     EnvE = "POSTGRES_USER"
	POSTGRES_PASSWORD EnvE = "POSTGRES_PASSWORD"
	POSTGRES_DB       EnvE = "POSTGRES_DB"
	POSTGRES_HOST     EnvE = "POSTGRES_HOST"
	POSTGRES_PORT     EnvE = "POSTGRES_PORT"
	POSTGRES_SSL_MODE EnvE = "POSTGRES_SSL_MODE"	
)
//	Constants to access environment variables needed to access Redis cache
const (	
	REDIS_HOST EnvE="REDIS_HOST"
	REDIS_PORT EnvE="REDIS_PORT"
	REDIS_PASSWORD EnvE="REDIS_PASSWORD"
)


const (	
	CONSENSYS_CLIENT_HOST EnvE="CONSENSYS_CLIENT_HOST"
	CONSENSYS_CLIENT_PORT EnvE="CONSENSYS_CLIENT_PORT"
)