package consts

type EnvE string

const (API_PORT EnvE ="API_PORT")
const (
	POSTGRES_USER     EnvE = "POSTGRES_USER"
	POSTGRES_PASSWORD EnvE = "POSTGRES_PASSWORD"
	POSTGRES_DB       EnvE = "POSTGRES_DB"
	POSTGRES_HOST     EnvE = "POSTGRES_HOST"
	POSTGRES_PORT     EnvE = "POSTGRES_PORT"
	POSTGRES_SSL_MODE EnvE = "POSTGRES_SSL_MODE"	
)

const (	
	CONSENSYS_CLIENT_HOST EnvE="CONSENSYS_CLIENT_HOST"
	CONSENSYS_CLIENT_PORT EnvE="CONSENSYS_CLIENT_PORT"
)